# Change the default Omarchy look'n'feel

general {
    border_size = 2
    col.active_border = 0xFFF1B100 0xFF00E500 45deg
    col.inactive_border = 0xFF004500
}

decoration {
    rounding = 8

    dim_inactive = true
    dim_strength = 0.15

    blur {
        size = 6
    }
}

animations {
    enabled = yes

    bezier = doom, 0.05, 0.9, 0.1, 1.05
    bezier = snap, 0.68, -0.55, 0.27, 1.55

    animation = windows, 1, 4, doom, slide
    animation = windowsOut, 1, 3, default, popin 80%
    animation = fade, 1, 4, doom
    animation = workspaces, 1, 4, snap, slidevert
}

layout {
}

plugin {
    dynamic-cursors {
        enabled = true
        mode = tilt
        threshold = 2

        shake {
            enabled = true
            threshold = 6.0
            factor = 1.5
        }
    }
}
